BadA:  #template: __A__
main:
    BadA:  #template: __A__
    Bad1A:  #template: __1A__
    Bad11A:  #template: __11A__
    settings:
        __1A__: Value1A
    sub:
        settings:
            __11A__: Value11A
        Bad11A:  #template: __11A__
    BadA:  #template: __A__
    Bad1A:  #template: __1A__
    Bad11A:  #template: __11A__
    deep:
        sub:
            sub2:
                settings:
                    __111A__: Value111A
                Bad111A:  #template: __111A__
settings:
    __A__: ValueA
